//! Roast lines per coaching tip. Several players in one match can get the same tip, so each
//! pool is large enough that they rarely get the same sentence.
//!
//! Lines are written about the player, never to the reader: the person who uploaded the
//! replay is only one of the six cars. Placeholders: `{name}` (gamertag), `{yours}` (the
//! player's value), `{theirs}` (the target tier's median) and `{next}` (plural rank name,
//! e.g. "Golds").

pub(super) const TOUCHES_PER_MINUTE: &[&str] = &[
    "The ball isn't lava. {next} touch it {theirs}, {name} managed {yours}.",
    "Spotted near the ball occasionally. {next} hit it {theirs}; {name}: {yours}.",
    "{yours} touches. {next}: {theirs}. The ball is the round thing in the middle.",
    "{name} touched the ball {yours}. {next} touch it {theirs}. It doesn't bite.",
    "Social distancing from the ball at {yours}. {next} get close: {theirs}.",
    "{next} hit the ball {theirs}. {name} hit it {yours}. Joining in is allowed.",
    "Ball contact: {yours}. {next}: {theirs}. Spectator mode is a different menu.",
    "{yours} touches? {next} average {theirs}. The ball has trust issues with {name} now.",
    "The ball was looking for {name}. {yours} touches vs {theirs} for {next}.",
    "{name} and the ball: {yours}. {next} and the ball: {theirs}. Long-distance relationship.",
    "{next} touch the ball {theirs}. This one: {yours}. The car has a hitbox for a reason.",
    "Touching the ball {yours}, {next} {theirs}. The casters forgot {name} was in the match.",
    "{yours} touches. {next} do {theirs}. Even the goal posts touched it more.",
    "\"I was rotating\" doesn't explain {yours} touches when {next} get {theirs}.",
    "{next}: {theirs} touches. {name}: {yours}. The ball misses them. Literally.",
    "Ball-shy at {yours}. {next} go for it {theirs}. Commit to something, {name}.",
    "{yours} touches. {next} at {theirs}. Ball-chasing is bad; ball-avoiding is worse.",
    "Technically in the lobby. {yours} touches vs {theirs} for {next}.",
    "{next} touch it {theirs}. {name} touched it {yours}. The ball filed a missing-person report.",
    "Fewer touches than a goalie in a coma: {yours}. {next}: {theirs}.",
    "{yours} touches. {next}: {theirs}. Drive at the ball. That's the whole game.",
];

pub(super) const FORWARD_TOUCH_FRACTION: &[&str] = &[
    "Only {yours} of {name}'s touches went toward the enemy net. {next}: {theirs}. Aim for the big net, bro.",
    "Hitting the ball is step one. Step two is the right direction: {next} send {theirs} forward, {name} {yours}.",
    "{yours} of their touches went forward. {next}: {theirs}. The enemy net is the other one.",
    "{next} push the ball upfield on {theirs} of touches. {name}: {yours}. Wrong way, champ.",
    "Forward touches: {yours}. {next}: {theirs}. Playing for both teams, apparently.",
    "{yours} of {name}'s hits went toward the enemy goal. {next} manage {theirs}. Read the field.",
    "The ball went forward off {yours} of their touches. {next}: {theirs}. Reverse is for parking.",
    "{next} hit it forward {theirs} of the time. {name}: {yours}. Their own net appreciates the attention.",
    "Only {yours} forward. {next}: {theirs}. Sideways is not a direction, it's a lifestyle.",
    "{name} sent {yours} of their touches toward the enemy net. {next} send {theirs}. Point the car the other way.",
    "{yours} forward touches. {next}: {theirs}. Every touch was an assist. For the other team.",
    "{next}: {theirs} of touches go forward. {name}: {yours}. Hit it through, not across.",
    "Direction matters. {next} go forward {theirs} of the time, {name} {yours}.",
    "{yours} of {name}'s touches helped. {next}: {theirs}. The rest were gifts.",
    "Forward touch rate {yours}. {next} hit {theirs}. Approach from behind the ball.",
    "It goes out, it comes back. {yours} forward vs {theirs} for {next}. Boomerang build.",
    "{next} move the ball toward the enemy net {theirs} of the time. {name}: {yours}. A ball return machine.",
    "{yours} forward. {next}: {theirs}. Turn around before hitting it.",
    "{name}'s touches go forward {yours} of the time. {next}: {theirs}. The opponents say thanks.",
    "{yours} of their hits went the right way. {next} land {theirs}. Line up the shots.",
];

pub(super) const MEAN_BALL_SPEED_AFTER_TOUCH: &[&str] = &[
    "{name}'s touches leave the ball at {yours}. {next} launch it at {theirs}. Hit it like it owes money.",
    "Gentle little taps at {yours}. {next} send it at {theirs}.",
    "Ball speed off {name}'s touches: {yours}. {next}: {theirs}. Flip into it.",
    "{yours}? {next} hit it at {theirs}. That's dribbling by accident.",
    "The ball leaves {name}'s car at {yours}. {next}: {theirs}. Commit to the hit.",
    "{next} send it at {theirs}. {name} sends it at {yours}. That's a pass to the goalie.",
    "{yours} off the bumper. {next}: {theirs}. Speed into the ball, not next to it.",
    "{name}'s shots travel at {yours}. {next}: {theirs}. The keeper had time to make coffee.",
    "Soft touch at {yours}. {next} hit at {theirs}. This isn't mini golf.",
    "{yours}. {next}: {theirs}. The ball barely noticed {name}.",
    "{next} smack it at {theirs}. {name} nudges it at {yours}. Polite, but useless.",
    "{name} hits the ball at {yours}. {next}: {theirs}. Use the nose of the car.",
    "Ball speed {yours}. {next}: {theirs}. Hit it, don't pet it.",
    "Front flip into it. {yours} off {name}'s touches, {theirs} for {next}.",
    "Touches at {yours}. {next}: {theirs}. The ball wants to go faster. Let it.",
    "{next} send it at {theirs}. {name}: {yours}. Trying to protect it?",
    "Shot power: {yours}. {next}: {theirs}. Drive through the ball.",
    "{yours} average off {name}'s hits. {next}: {theirs}. Bumper-car energy.",
    "{next} hit the ball at {theirs}. {name}'s touches average {yours}. Hug it less.",
    "The ball floats away at {yours}. {next} send it at {theirs}. Boost into the touch.",
];

pub(super) const BOOST_EMPTY_FRACTION: &[&str] = &[
    "On zero boost {yours} of the game. {next}: {theirs}. The pads are free, grab some.",
    "{name} ran on fumes {yours} of the time ({next}: {theirs}). Boost is not a collectible.",
    "Empty tank {yours} of the game. {next}: {theirs}. The boost button isn't a fidget toy.",
    "{yours} of the match at zero boost. {next} sit there {theirs}. Feather it, {name}.",
    "{next} are empty {theirs} of the time. {name}: {yours}. Boost management is a thing.",
    "Zero boost for {yours} of the game. {next}: {theirs}. Nobody saves anything on empty.",
    "{name}'s boost gauge sat at 0 for {yours}. {next}: {theirs}. Grab a pad on the way back.",
    "Empty {yours} of the time. {next}: {theirs}. Supersonic is not the default speed.",
    "{yours} of the game with no boost. {next}: {theirs}. Every challenge, at a disadvantage.",
    "Dry tank {yours} of the match ({next}: {theirs}). Fill up between plays.",
    "{next} run out {theirs} of the time. {name}: {yours}. Boost is a resource, not a vibe.",
    "Out of boost {yours} of the game. {next}: {theirs}. Let go of the button sometimes.",
    "{yours} at zero. {next}: {theirs}. {name} boosts like the next pad is guaranteed.",
    "Empty for {yours} of it. {next} manage {theirs}. Plan a path through the pads.",
    "{next}: empty {theirs} of the match. {name}: {yours}. Stop boosting into the wall.",
    "{yours} of the game on fumes. {next}: {theirs}. The boost gauge isn't decoration.",
    "{name}'s boost meter read zero {yours} of the time. {next}: {theirs}. Collect, then spend.",
    "{yours} empty. {next}: {theirs}. Boosting while supersonic does nothing, by the way.",
    "Zero boost {yours} of the game ({next}: {theirs}). Steal the other team's if needed.",
    "{next} keep fuel in the tank, empty only {theirs} of the time. {name}: {yours}.",
];

pub(super) const SMALL_PADS_PER_MINUTE: &[&str] = &[
    "Small pads exist. {next} grab {theirs}, {name} grabs {yours}. Stop driving past the snacks.",
    "{yours} small pads. {next}: {theirs}. Big boost isn't the only food group.",
    "{next} pick up {theirs} small pads. {name}: {yours}. Path through them.",
    "Small pad pickups: {yours}. {next}: {theirs}. They respawn fast for a reason.",
    "{name} ignores small pads ({yours}). {next} grab {theirs}. Twelve boost adds up.",
    "{yours} small pads. {next} hoover up {theirs}. Be a vacuum.",
    "{next}: {theirs} small pads. {name}: {yours}. Rotate through the pads, not around them.",
    "Small pads at {yours}. {next}: {theirs}. Corner boost isn't a meeting point.",
    "{yours} small pads collected. {next}: {theirs}. They're on the floor, glowing, right there.",
    "{next} snack on small pads {theirs}. {name}: {yours}. Graze more.",
    "{name} takes {yours} small pads, {next} take {theirs}. Free boost, zero effort.",
    "{yours}. {next}: {theirs}. Small pads are why they never run out.",
    "{next} grab {theirs} small pads. {name}: {yours}. Stop full-boost hunting.",
    "Small pads: {yours}. {next}: {theirs}. Drive over the dots.",
    "{yours} small pads? {next} average {theirs}. The pads aren't decoration either.",
    "{next} collect {theirs} small pads. {name}: {yours}. Learn the pad paths.",
    "Drove past free boost all game: {yours} small pads vs {theirs} for {next}.",
    "Small pad rate {yours}. {next}: {theirs}. Every pad is a little gift.",
    "{yours} small pads. {next}: {theirs}. {name}'s boost problems start here.",
    "{next} pick up small pads {theirs}. {name}: {yours}. Boost doesn't only come in 100.",
];

pub(super) const SUPERSONIC_FRACTION: &[&str] = &[
    "Supersonic {yours} of the time. {next}: {theirs}. The fast button is right there.",
    "{next} hit top speed {theirs} of the game. {name}: {yours}. Sunday drive?",
    "Supersonic {yours}. {next}: {theirs}. The car has more than one gear.",
    "{yours} of the game at full speed. {next}: {theirs}. Speed is a mechanic.",
    "{next} go supersonic {theirs} of the time. {name}: {yours}. Handbrake still on?",
    "Top speed for {yours} of the game. {next}: {theirs}. Floor it.",
    "{yours} supersonic. {next}: {theirs}. The trail behind {name}'s car is shy.",
    "{next} are supersonic {theirs} of the match. {name}: {yours}. Tour bus energy.",
    "Supersonic only {yours} of the time. {next}: {theirs}. Faster rotations, faster everything.",
    "{yours} at top speed. {next}: {theirs}. {name} drives like there's a speed camera.",
    "{next} spend {theirs} of the game supersonic. {name}: {yours}. Get to the ball first.",
    "Full speed {yours} of the game ({next}: {theirs}). Slow is not safe.",
    "{yours} supersonic. {next}: {theirs}. Keeping momentum is a skill.",
    "{next} reach supersonic {theirs} of the time, {name} {yours}. Gotta go fast.",
    "Supersonic {yours} of the game. {next}: {theirs}. It's Rocket League, not Rocket Stroll.",
    "{yours} at max speed. {next}: {theirs}. The other team waited for {name}.",
    "{next} are flying across the pitch {theirs} of the time. {name}: {yours}. Hurry up.",
    "Top speed {yours}, {next} {theirs}. Cruise control off.",
    "{yours} of the time supersonic. {next}: {theirs}. Momentum is free boost.",
    "{next} max out their speed {theirs} of the game. {name}: {yours}. Pedal, meet metal.",
];

pub(super) const SLOW_FRACTION: &[&str] = &[
    "Basically parked {yours} of the game. {next} only crawl {theirs}.",
    "Slow for {yours} of the match. {next}: {theirs}. Keep the wheels turning.",
    "{yours} of the game at walking pace. {next}: {theirs}. Move, {name}.",
    "{next} crawl only {theirs} of the time. {name} crawls {yours}. Is the car on?",
    "Crawling {yours} of the time. {next}: {theirs}. Standing still is not positioning.",
    "{yours} of the match spent slow. {next}: {theirs}. The ball won't come to {name}.",
    "Slow {yours}. {next}: {theirs}. A very expensive traffic cone.",
    "{next} are slow {theirs} of the time. {name}: {yours}. Throttle is the right trigger.",
    "{yours} at a crawl. {next}: {theirs}. Did {name} go AFK?",
    "Parked {yours} of the game ({next}: {theirs}). The goal posts move more.",
    "{yours} crawling. {next}: {theirs}. Stay in motion; stopping costs time.",
    "{next} only slow down {theirs} of the time. {name}: {yours}. Parallel parking practice?",
    "Slow {yours} of the game. {next}: {theirs}. Every stop is a lost second.",
    "{yours} of the match below walking speed. {next}: {theirs}. Snail mode on.",
    "{next} crawl {theirs}. {name} crawls {yours}. Keep it rolling.",
    "{name} was slow {yours} of the time. {next}: {theirs}. Shadow defence still means moving.",
    "{yours} of the game at a crawl ({next}: {theirs}). The minimap thought {name} disconnected.",
    "Slow time: {yours}. {next}: {theirs}. Momentum lost is boost wasted.",
    "{yours} slow. {next}: {theirs}. Rocket League has no pit stops.",
    "{next} sit slow {theirs} of the match. {name} sat {yours}. Get comfy somewhere else.",
];

pub(super) const OVERCOMMIT_FRACTION: &[&str] = &[
    "Upfield while a teammate had the ball {yours} of the time ({next}: {theirs}). The net misses {name}.",
    "Ahead of the play {yours} of the game. {next}: {theirs}. Someone has to rotate back. It's {name}.",
    "{yours} of the time {name} was upfield with a teammate on the ball. {next}: {theirs}. Who's home?",
    "{next} overcommit {theirs} of the time. {name}: {yours}. Leave someone at home.",
    "Overcommitted {yours} of the game. {next}: {theirs}. The net is lonely.",
    "{yours} of the time, everyone was forward, {name} included. {next}: {theirs}. Last man back is a job.",
    "Pushing up {yours} of the time while a teammate had it. {next}: {theirs}. Give them space.",
    "{next} overcommit only {theirs}. {name}: {yours}. The other team's counter-attack says thanks.",
    "Upfield {yours} of the time with a teammate on the ball. {next}: {theirs}. Trust them and cover.",
    "{yours} overcommitted. {next}: {theirs}. Not every play needs {name} in it.",
    "{next}: {theirs}. {name}: {yours}. Rotations aren't a suggestion.",
    "Too far up {yours} of the time ({next}: {theirs}). The goalie is a ghost.",
    "{yours} of the game in the enemy half while a teammate had it. {next}: {theirs}. Back post exists.",
    "Overcommits: {yours}. {next}: {theirs}. All gas, no defense.",
    "{name} joined every attack: {yours} overcommitted vs {theirs} for {next}. Pick the moments.",
    "{yours} of the time, three cars went forward and one was {name}. {next}: {theirs}.",
    "{next} overcommit {theirs} of the time. {name}: {yours}. Someone has to be third man.",
    "Upfield {yours}, {next} {theirs}. The teammate didn't need a cheerleader.",
    "{yours} overcommitted. {next}: {theirs}. Free goals for the other team, courtesy of {name}.",
    "Overextended {yours} of the time ({next}: {theirs}). Back to the net.",
    "{yours} of the game playing striker with a teammate on the ball. {next}: {theirs}. Read the play.",
];

pub(super) const GOAL_SIDE_WHEN_DEFENDING_FRACTION: &[&str] = &[
    "When the other team attacked, {name} was on the right side of the ball {yours} of the time. {next}: {theirs}. Defend from goal-side.",
    "Goal-side on defense {yours} of the time. {next}: {theirs}. Get between the ball and the net.",
    "{next} are goal-side when defending {theirs} of the time. {name}: {yours}. Wrong side of the ball.",
    "Goal-side on defense: {yours}. {next}: {theirs}. Nobody saves it from behind.",
    "{yours} goal-side under attack. {next}: {theirs}. Defense starts with position.",
    "{next} stay goal-side {theirs} of the time. {name}: {yours}. Chasing from behind is not defense.",
    "When it mattered, {name} was goal-side {yours} of the time ({next}: {theirs}). Back post, please.",
    "Goal-side {yours}. {next}: {theirs}. The ball is supposed to come at {name}, not past them.",
    "{yours} of defending time spent goal-side. {next}: {theirs}. Turn around earlier.",
    "{next} defend from goal-side {theirs} of the time. {name}: {yours}. Rotate back, then face the play.",
    "On defense, goal-side only {yours}. {next}: {theirs}. The net is behind the car, ideally.",
    "{yours} goal-side. {next}: {theirs}. Shadow, don't chase.",
    "Under attack, {name} was goal-side {yours} of the time. {next}: {theirs}. Spectating the goals against.",
    "{next}: {theirs} goal-side. {name}: {yours}. Between ball and net is the whole idea.",
    "Defensive positioning: {yours}. {next}: {theirs}. Nobody blocks from the wrong side.",
    "Goal-side {yours} of the time on defense ({next}: {theirs}). Stop defending from the enemy half.",
    "{yours} in position when the other team pushed. {next}: {theirs}. Get back before challenging.",
    "{next} are between the ball and their net {theirs} of the time on defense. {name}: {yours}.",
    "{yours} goal-side on defense. {next}: {theirs}. Watching from behind the ball isn't defending.",
    "Under pressure, {name} was goal-side {yours}. {next}: {theirs}. Back-post rotations.",
];

pub(super) const DOUBLE_COMMIT_FRACTION: &[&str] = &[
    "Double-committing {yours} of the time ({next}: {theirs}). The teammate had it. Probably.",
    "{name} went for the same ball as a teammate {yours} of the time. {next}: {theirs}. One car per ball.",
    "{next} double commit {theirs}. {name}: {yours}. Let the teammate have it.",
    "Double commits: {yours}. {next}: {theirs}. Two cars, one ball, zero goals.",
    "{yours} of the time {name} challenged alongside a teammate. {next}: {theirs}. Check where they are.",
    "{next} double-commit only {theirs} of the time. {name}: {yours}. Trust the teammate.",
    "{yours} double commits ({next}: {theirs}). The teammate wanted that touch.",
    "Double-committing {yours}. {next}: {theirs}. The other team loves {name} for it.",
    "{yours}. {next}: {theirs}. \"Mine\" is not a team strategy.",
    "{name} and a teammate went for it together {yours} of the time. {next}: {theirs}. Synchronised whiffing.",
    "{next} double commit {theirs} of the time. {name}: {yours}. Look before leaping.",
    "Double commits at {yours}. {next}: {theirs}. \"Sorry!\" spam incoming.",
    "{yours} double commits. {next}: {theirs}. Read the teammate's approach.",
    "Same ball, two cars, {yours} of the time. {next}: {theirs}. Someone has to back off. {name}.",
    "{next}: {theirs}. {name}: {yours}. Two cars on the ball is an open net.",
    "{yours} of challenges shared with a teammate. {next}: {theirs}. It's not a group project.",
    "Double-commit rate {yours}. {next}: {theirs}. Learn when to cover instead.",
    "{yours} double commits. {next}: {theirs}. Bumping a teammate isn't a demo.",
    "{name} doubled up {yours} of the time. {next}: {theirs}. Hold the position.",
    "Double commits: {yours}. {next}: {theirs}. That \"Whoops...\" was earned.",
];

pub(super) const GOAL_SIDE_AFTER_TOUCH_FRACTION: &[&str] = &[
    "After touching the ball {name} got back goal-side {yours} of the time ({next}: {theirs}). Stop admiring the touch.",
    "Back goal-side after a touch {yours} of the time. {next}: {theirs}. Hit and rotate.",
    "{next} recover goal-side after a touch {theirs} of the time. {name}: {yours}. Don't stay in the play.",
    "{yours} goal-side after touching it. {next}: {theirs}. The touch was not that good.",
    "After each touch, back goal-side {yours} of the time. {next}: {theirs}. Touch, then leave.",
    "{yours}. {next}: {theirs}. Touching the ball is not a reason to stay upfield, {name}.",
    "{next} rotate back after their touch {theirs} of the time. {name}: {yours}. Rotation means rotating.",
    "Post-touch recovery: {yours}. {next}: {theirs}. The play continues without {name}.",
    "{name} got goal-side after touches {yours} of the time. {next}: {theirs}. Back post after the hit.",
    "{yours} after-touch recovery. {next}: {theirs}. Hit it and go home.",
    "{next} get back goal-side {theirs} of the time after touching it. {name}: {yours}. Stop waiting for the replay.",
    "Goal-side after a touch: {yours}. {next}: {theirs}. Nobody's clapping. Rotate.",
    "{yours} of the time {name} recovered after a touch. {next}: {theirs}. Every touch ends in a rotation.",
    "After the touch, {yours} goal-side. {next}: {theirs}. Don't watch the ball, drive back.",
    "{next}: {theirs} goal-side after touching. {name}: {yours}. That touch became a counter-attack.",
    "{yours} back in position after touching the ball. {next}: {theirs}. Hit, then cover.",
    "Touch it and stay there: {yours} recovered vs {theirs} for {next}.",
    "Getting back after touches: {yours}. {next}: {theirs}. Rotation starts at the touch.",
    "{yours}. {next}: {theirs}. The ball doesn't need {name} after the hit. The net does.",
    "After hitting it {name} went goal-side {yours} of the time. {next}: {theirs}. Hang around less.",
];

pub(super) const KICKOFF_WIN_FRACTION: &[&str] = &[
    "Won {yours} of the kickoffs. {next}: {theirs}. Practise one kickoff. Any kickoff.",
    "Kickoff wins: {yours}. {next}: {theirs}. Speed flip tutorials exist.",
    "{next} win {theirs} of kickoffs. {name}: {yours}. Flip into the ball, not near it.",
    "{yours} kickoffs won. {next}: {theirs}. Did {name} fake every one?",
    "{name} won {yours} of their kickoffs. {next}: {theirs}. Free play has a kickoff button.",
    "{next}: {theirs} kickoff wins. {name}: {yours}. The first touch of the game matters.",
    "Kickoffs won {yours}. {next}: {theirs}. Boost, flip, hit. Three steps.",
    "{yours} kickoff wins ({next}: {theirs}). Stop losing the free 50/50.",
    "{next} win kickoffs {theirs} of the time. {name}: {yours}. Aim at the middle of the ball.",
    "{yours} of kickoffs won. {next}: {theirs}. Kickoff practice, ten minutes a day.",
    "Kickoff record: {yours}. {next}: {theirs}. Every lost kickoff is a free attack.",
    "{yours}. {next}: {theirs}. {name} is losing the one play that can be rehearsed.",
    "{next} take {theirs} of kickoffs. {name} takes {yours}. The diagonal flip is a thing.",
    "Won {yours} of kickoffs. {next}: {theirs}. Hit it with the nose, not the side.",
    "{yours} kickoffs. {next} win {theirs}. The countdown is a warning, not decoration.",
    "Kickoff success {yours}. {next}: {theirs}. Learn a speed flip, or at least a fast flip.",
    "{next} win the kickoff {theirs} of the time. {name}: {yours}. It's the same play after every goal.",
    "{yours} kickoffs won. {next}: {theirs}. Go when it says go.",
    "{name}'s kickoff is a coin flip at best: {yours} won, {next} win {theirs}.",
    "Kickoffs: {yours}. {next}: {theirs}. Stop braking before the ball.",
];

pub(super) const DEMOS_RECEIVED: &[&str] = &[
    "Demolished {yours} times. {next}: {theirs}. Check the mirrors.",
    "{yours} demos taken. {next}: {theirs}. {name} is a scrap yard.",
    "{next} get demoed {theirs} times. {name}: {yours}. Look around.",
    "Exploded {yours} times. {next}: {theirs}. Jump when they come.",
    "{yours} demos received. {next}: {theirs}. {name} is a free kill.",
    "Blown up {yours} times ({next}: {theirs}). Watch the bumpers behind.",
    "{next} get demolished {theirs} times. {name}: {yours}. Respawn timer enjoyer.",
    "Demolished {yours} times. {next}: {theirs}. A little hop goes a long way.",
    "{yours} demos. {next}: {theirs}. {name}'s car insurance is through the roof.",
    "{name} got demoed {yours} times. {next}: {theirs}. Someone on the other team really likes them.",
    "{next} explode {theirs} times. {name} explodes {yours}. Stop driving in straight lines.",
    "{yours} demos taken. {next}: {theirs}. Supersonic cars coming straight in are a hint.",
    "Demolished {yours} times ({next}: {theirs}). More time respawning than playing.",
    "{yours}. {next}: {theirs}. Turn ball cam off now and then, {name}.",
    "{next} take {theirs} demos. {name}: {yours}. Situational awareness, please.",
    "{yours} demos received. {next}: {theirs}. The enemy bumpers know {name} by name.",
    "Exploded {yours} times this match. {next}: {theirs}. Dodge the demo, not the ball.",
    "{yours} times demolished. {next}: {theirs}. {name} was a target, not a player.",
    "Demos received: {yours}. {next}: {theirs}. Boost sound from behind? Move.",
    "{next} get blown up {theirs} times. {name}: {yours}. Piñata season is over.",
];

pub(super) const DODGES_PER_MINUTE: &[&str] = &[
    "Flips: {yours}. {next}: {theirs}. Flipping is free speed.",
    "{yours} dodges. {next}: {theirs}. The jump button works twice.",
    "{next} flip {theirs}. {name}: {yours}. Front flip to go faster without boost.",
    "Dodging {yours}. {next}: {theirs}. The car can do flips. It was built for it.",
    "{yours} flips. {next}: {theirs}. All four wheels on the ground is not a rule.",
    "{next} dodge {theirs}. {name}: {yours}. Flip into the ball for power.",
    "Dodges: {yours}. {next}: {theirs}. Double-tap that jump.",
    "{yours} flips? {next} manage {theirs}. Flip resets can wait; start with flips.",
    "{name} flips {yours}. {next}: {theirs}. Speed without boost is right there.",
    "Gymnastics score: {yours}. {next}: {theirs}. Flip more, {name}.",
    "{yours} dodges. {next}: {theirs}. Flip toward the ball, flip toward the play.",
    "{next}: {theirs} flips. {name}: {yours}. The car is not a tractor.",
    "Dodge rate {yours}. {next}: {theirs}. Flips are how they get there first.",
    "{yours} flips. {next}: {theirs}. Shots without a flip are passes.",
    "{next} flip {theirs} while {name} flips {yours}. Jump, then jump again.",
    "{yours} dodges. {next}: {theirs}. Flip after landing to keep the speed.",
    "Flipping {yours}. {next}: {theirs}. The car has a second jump. Use it.",
    "{yours}. {next}: {theirs}. Dodge into challenges, not just into walls.",
    "{next} dodge {theirs}. {name}: {yours}. Driving like a bus.",
    "Flips: {yours}. {next}: {theirs}. Free speed, free power, free style.",
];

pub(super) const HIGH_AIR_FRACTION: &[&str] = &[
    "{next} spend {theirs} of the game airborne. {name}: {yours}. Gravity is optional.",
    "Grounded {yours} of the way, metaphorically. {next} fly {theirs} of the game.",
    "In the air {yours} of the time. {next}: {theirs}. The ball goes up too, believe it or not.",
    "{yours} airborne. {next}: {theirs}. {name}'s car has wings in spirit only.",
    "{next} fly {theirs} of the match. {name}: {yours}. Look up.",
    "Airtime: {yours}. {next}: {theirs}. The ceiling is part of the map.",
    "{yours} of the game in the air. {next}: {theirs}. Floor-locked.",
    "{next} are airborne {theirs} of the time. {name}: {yours}. Jump. Boost. Repeat.",
    "Up high {yours} of the game ({next}: {theirs}). Aerials are the next step.",
    "{yours} air time. {next}: {theirs}. The sky misses {name}.",
    "{next} live in the air {theirs} of the time. {name}: {yours}. Leave the ground occasionally.",
    "{yours} airborne. {next}: {theirs}. The ball won't always come back down.",
    "Flying {yours} of the match. {next}: {theirs}. Aerial training packs are free.",
    "{next}: {theirs} airborne. {name}: {yours}. The wheels are getting all the attention.",
    "{yours} of the game off the ground. {next}: {theirs}. Contest the high balls.",
    "Air time {yours}. {next}: {theirs}. {name} is playing it like a racing game.",
    "{next} take to the sky {theirs} of the time. {name}: {yours}. Take off.",
    "{yours} in the air. {next}: {theirs}. Up is a direction too.",
    "Altitude: {yours}. {next}: {theirs}. Boost points up as well as forward.",
    "{next} fly {theirs}. {name} flies {yours}. Ground game only gets so far.",
];

pub(super) const AERIAL_TOUCH_FRACTION: &[&str] = &[
    "{yours} of {name}'s touches were in the air. {next}: {theirs}. Free play is free.",
    "Aerial touches: {yours}. {next}: {theirs}. Meet the ball before it lands.",
    "{next} hit {theirs} of their touches in the air. {name}: {yours}. Stop waiting for the bounce.",
    "{yours} aerial touches. {next}: {theirs}. The ball spends time up there; so should {name}.",
    "{next}: {theirs} in the air. {name}: {yours}. Leaving the ground is a skill.",
    "Only {yours} of the touches airborne. {next}: {theirs}. Look up, jump up.",
    "{yours} aerial. {next}: {theirs}. The ball doesn't need to touch grass first.",
    "{next} take {theirs} of touches in the air. {name}: {yours}. Challenge the high balls.",
    "{yours} of touches in the air ({next}: {theirs}). Aerial training: ten minutes, daily.",
    "Air touches at {yours}. {next}: {theirs}. The car can fly; it just doesn't with {name} driving.",
    "{yours}. {next}: {theirs}. The bounce isn't {name}'s friend.",
    "{next} touch it in the air {theirs} of the time. {name}: {yours}. Get off the floor.",
    "Aerial share {yours}. {next}: {theirs}. The opponents are winning every high ball.",
    "{yours} of the hits mid-air. {next}: {theirs}. Jump earlier.",
    "{next} play the air {theirs} of the time. {name}: {yours}. Gravity wins too often.",
    "{yours} aerial touches. {next}: {theirs}. {name} is a ground type.",
    "In-air touches: {yours}. {next}: {theirs}. Hold jump longer, boost sooner.",
    "{yours} of {name}'s touches airborne. {next}: {theirs}. The ceiling is not a myth.",
    "{next}: {theirs} aerial touches. {name}: {yours}. Meet it up there.",
    "{name} lets the ball land: only {yours} air touches vs {theirs} for {next}.",
];

pub(super) const FAST_AERIAL_FRACTION: &[&str] = &[
    "{name}'s aerials take the scenic route: {yours} fast aerials vs {theirs} for {next}. Jump, jump, boost.",
    "Fast aerials: {yours}. {next}: {theirs}. Double-jump while boosting.",
    "{next} fast aerial {theirs} of the time. {name}: {yours}. Slow aerials get beaten to the ball.",
    "{yours} fast aerials. {next}: {theirs}. {name}'s takeoffs need a runway.",
    "{next}: {theirs} fast aerials. {name}: {yours}. Jump, tilt, jump, boost.",
    "Fast aerial rate {yours}. {next}: {theirs}. Training packs are calling.",
    "{yours} of {name}'s aerials were fast. {next}: {theirs}. The ball won't wait.",
    "{next} get up fast {theirs} of the time. {name}: {yours}. Those aerials have a loading screen.",
    "{yours} fast aerials ({next}: {theirs}). Second jump, earlier.",
    "Takeoff speed: {yours} fast. {next}: {theirs}. Slow liftoff, late touch.",
    "{yours}. {next}: {theirs}. A fast aerial beats a fancy one.",
    "{next} launch fast {theirs} of the time. {name}: {yours}. Boost before the first jump ends.",
    "{yours} fast aerials. {next}: {theirs}. The other team got there first. Again.",
    "Fast aerials {yours}, {next} {theirs}. Hold jump, tap jump, hold boost.",
    "{next} rocket up {theirs} of the time. {name}: {yours}. Floating like a balloon.",
    "{yours} fast aerials. {next}: {theirs}. {name}'s aerials are on dial-up.",
    "{next}: {theirs}. {name}: {yours}. Practise fast aerials until they're boring.",
    "Fast aerials at {yours}. {next}: {theirs}. Every frame counts up there.",
    "{yours} of aerials done fast. {next}: {theirs}. Hot-air balloon aerials won't cut it.",
    "{next} fast aerial {theirs}. {name}: {yours}. Get to the ball before the other team does.",
];

pub(super) const WAVEDASH_LIKE_DODGES_PER_MINUTE: &[&str] = &[
    "{next} wavedash {theirs}. {name}: {yours}. Land with some style.",
    "Wavedashes: {yours}. {next}: {theirs}. Free speed on every landing.",
    "{yours} wavedashes. {next}: {theirs}. Flip just before landing.",
    "{next} wavedash {theirs}. {name}: {yours}. Landings can be fast.",
    "{yours} wavedashes. {next}: {theirs}. Recovery is speed.",
    "Wavedash rate {yours}. {next}: {theirs}. Touch down with a flip.",
    "{next}: {theirs} wavedashes. {name}: {yours}. Landing like a brick.",
    "{yours}. {next}: {theirs}. Every landing is free speed with a wavedash.",
    "{next} wavedash off landings {theirs}. {name}: {yours}. Stick the landing, then flip.",
    "{name} wavedashes {yours}. {next}: {theirs}. That car lands like it's tired.",
    "{yours} wavedashes. {next}: {theirs}. Tilt back, flip as the wheels hit.",
    "{next} wavedash {theirs}. {name}: {yours}. Recoveries are part of the game.",
    "Wavedashes {yours}, {next} {theirs}. Slow recoveries lose challenges.",
    "{yours}. {next}: {theirs}. Wavedash out of every landing.",
    "{next} chain wavedashes {theirs}. {name}: {yours}. Fancy and fast.",
    "{yours} wavedashes ({next}: {theirs}). Learn it once, use it forever.",
    "Landing speed: {yours} wavedashes. {next}: {theirs}. Momentum matters.",
    "{next}: {theirs}. {name}: {yours}. Off the wall, wavedash, back in play.",
    "{yours} wavedashes. {next}: {theirs}. Every landing is a chance.",
    "{next} wavedash {theirs} while {name} does {yours}. Free play, five minutes.",
];

pub(super) const POWERSLIDE_FRACTION: &[&str] = &[
    "Powersliding {yours} of the time, {next} {theirs}. Turning is a skill and there's a button for it.",
    "Powerslide use: {yours}. {next}: {theirs}. Tight turns win challenges.",
    "{next} powerslide {theirs} of the time. {name}: {yours}. Stop doing three-point turns.",
    "{yours} powersliding. {next}: {theirs}. {name}'s turning circle is a parking lot.",
    "{next}: {theirs}. {name}: {yours}. The handbrake is not for emergencies only.",
    "Sliding {yours} of the match. {next}: {theirs}. Drift into position.",
    "{yours} powerslide. {next}: {theirs}. Those turns need their own postcode.",
    "{next} drift {theirs} of the game. {name}: {yours}. Tokyo Drift is homework.",
    "Powerslide {yours}. {next}: {theirs}. Quick turns, quick plays.",
    "{yours} of the time sliding. {next}: {theirs}. Turn around faster.",
    "{next} powerslide {theirs}. {name}: {yours}. Turning like a cruise ship.",
    "{yours}. {next}: {theirs}. Powerslide to turn tight around the ball.",
    "Handbrake use: {yours}. {next}: {theirs}. Those corners are wide.",
    "{next} slide into position {theirs} of the time. {name}: {yours}. Get there faster.",
    "{yours} powersliding ({next}: {theirs}). {name}'s car turns like a semi truck.",
    "Powerslide time {yours}. {next}: {theirs}. Slide, then boost.",
    "{next}: {theirs} powerslide. {name}: {yours}. Learn to cut corners.",
    "{yours} of the game drifting. {next}: {theirs}. There's a button. It's great.",
    "{next} use powerslide {theirs} of the time. {name}: {yours}. Tight turns save seconds.",
    "Turning circle report: {yours} powerslide vs {theirs} for {next}. Use the button.",
];

/// Lines for a player with nothing left to learn from the rank above (or already SSL).
pub(super) const NOTHING_TO_FIX: &[&str] = &[
    "Honestly? Nothing to fix. Suspicious.",
    "No notes. {name} can go touch grass instead.",
    "Nothing to roast. We checked twice.",
    "Clean game. Annoyingly clean.",
    "No notes. The coach is speechless.",
    "Nothing to fix. Is {name} sure this is the right lobby?",
    "Couldn't find a weakness. We'll keep looking.",
    "Flawless by the numbers. The numbers might be lying.",
    "Nothing to fix. {name}, share the settings.",
    "No roast available. Please play worse next time, {name}.",
    "Played like the rank above. Smurf behaviour.",
    "Zero complaints. That's a first.",
    "Already doing what the next rank does. Go climb.",
    "Nothing to fix. The teammates should read this one.",
    "Clean sheet of stats. Disgusting.",
    "No notes. The roast writers are on strike.",
    "We tried to roast {name}. {name} didn't let us.",
    "Nothing to fix. The rank is the only thing holding {name} back.",
    "Perfect report card. Queue up again.",
    "Nothing to improve here. Ego check pending.",
];
