[config]
default_to_workspace = false
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = true
# Skips loading the current crate related environment variables
skip_crate_env_info = true

[tasks.sqlx-offline]
command = "cargo"
args = ["sqlx", "prepare", "--workspace"]

[tasks.upgrade]
dependencies = ["upgrade-internal", "update"]

[tasks.upgrade-internal]
command = "cargo"
args = ["upgrade", "-i", "-v"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.start-web]
cwd = "crates/web_predictor"
command = "dx"
args = ["serve"]
